---
apiVersion: v1
kind: Service
metadata:
  name: ambassador-pro-auth
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  AuthService
      name:  authentication
      auth_service: ambassador-pro-auth
      allowed_headers:
       - "Authorization"
       - "Client-Id"
       - "Client-Secret"
spec:
  selector:
    service: ambassador-pro-auth
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ambassador-pro
rules:
- apiGroups: ["stable.datawire.io"]
  resources:
  - policies
  verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ambassador-pro
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ambassador-pro
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ambassador-pro
subjects:
- kind: ServiceAccount
  name: ambassador-pro
# Ensure Your namespace is configured correctly
  namespace: default
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ambassador-pro-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      service: ambassador-pro-auth
  template:
    metadata:
      labels:
        service: ambassador-pro-auth
    spec:
      serviceAccountName: ambassador-pro
      containers:
      - name: ambassador-pro
        image: quay.io/datawire/ambassador_pro:auth-0.0.6
        ports:
        - containerPort: 8080
        env:
#         Configure to your callback URL
          - name: AUTH_CALLBACK_URL
            value: "http://localhost/callback"
#         Configure to your Auth0 domain
          - name: AUTH_DOMAIN
            value: "datawire-oss.auth0.com"
#         Configure to your Auth0 API Audience
          - name: AUTH_AUDIENCE
            value: "https://datawire-oss.auth0.com/api/v2/"
#         Configure to your Auth0 Application client ID
          - name: AUTH_CLIENT_ID
            value: "4OZnBrPiiBl4i5tcVgX6AfSt1dXT5R8r"
#          Uncomment if you want the Auth0 management API to validate your configurations
#          - name: AUTH_CLIENT_SECRET
#            value: <CLIENT SECRET>
      imagePullSecrets:
      - name: ambassador-pro-registry-credentials
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: policies.stable.datawire.io
spec:
  group: stable.datawire.io
  version: v1beta1
  versions:
    - name: v1beta1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: policies
    singular: policy
    kind: Policy
    shortNames:
    - pol
