# NOTE: If you use a `/` for example google.com/abcd/ <<< ambassador-pro
# expects the route to be as specfied. As a precaution, consider adding
# another Mapping. Look below for specification.
# IMPORTANT: Mappings need unique names.
---
apiVersion: v1
kind: Service
metadata:
  name: containername
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  container_mapping_one
      prefix: /containername
      service: containername
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  container_mapping_two
      prefix: /containername/
      service: containername
spec:
  selector:
    app: containername
  ports:
  - port: 80
    name: container-name-api
    targetPort: http-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: containername
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: containername
    spec:
      containers:
      - name: containername
        image: container_name_image:v1
        ports:
        - name: http-api
          containerPort: 8080
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi
